### ISSUE TITLE
Breadcrumbs navigation 

### ISSUE THREAD

**Issue by leefaisonr** [pulibrary/imagecat-rails#140]
### User story

As a user, I want to be able to navigate the site by clicking through GuideCards and their respective SubGuideCards and have a tree-structure exist as I click through.

### Acceptance criteria

- [ ] A tree-structure exists on the site and is built as I navigate through SubGuideCards
- [ ] If I click on a parent of a SubGuide, it will take me back to that page that lists their SubGuide links
- [ ] The structure is present at the top of the page when I get to my desired SubGuideCard

### Concrete example

findingaids.princeton.edu

### Implementation notes, if any

https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/

**Comment by hackartisan** [comment]
This seemed lower priority; closing as wontfix
