### ISSUE TITLE
Upgrade to latest Postgres

### ISSUE THREAD

**Issue by bess** [pulibrary/imagecat-rails#147]
We need to get off of PostgeSQL 13 (See https://github.com/pulibrary/princeton_ansible/issues/4246). We need to upgrade imagecat to use the latest version of postgres. 

See https://github.com/pulibrary/princeton_ansible/blob/main/group_vars/imagecat_rails/main.yml#L3

## Acceptance criteria
- [x] Imagecat servers are re-built to use latest version of postgres
- [x] Data is re-imported

**Comment by hackartisan** [comment]
We need to point prod back at the old db for our demo. So re opening this to do that migration again. However, it's blocked for now.

**Comment by hackartisan** [comment]
All the data is loaded and we can re-migrate now.
