### ISSUE TITLE
"more information" feature

### ISSUE THREAD

**Issue by bess** [pulibrary/imagecat-rails#169]
Some guide cards (see, e.g., "United States") have a "more info" link. Find these info files and display them. 

We have a bunch of html files. They are named like "a" through "zz". These correspond to GuideCards with path values, which look like "info/N," for example.

implementation
- [x] add the files to the repo
- [x] create a new model, InfoCard
- [x] load the contents of each file into the database
- [x] make the html of the info cards show up on a guide card page that has the corresponding path

here's how it looks in the legacy site:
![image](https://github.com/pulibrary/imagecat-rails/assets/845363/f52987df-58f3-4e3a-9213-08eca8f61c04)

We don't think we need the "for more information click here" bit. The way it's currently listed on our new site looks fine.

**Comment by hackartisan** [comment]
So this is kind of interesting.

```
> GuideCard.where("path LIKE 'info%'").map(&:path).uniq
=> ["info/N", "info/EE", "info/A", "info/HH", "info/TT", "info/P", "info/H", "info/U"]
```

only 8 of them are actually used.

**Comment by hackartisan** [comment]
Reopening; it looks like we need to run the task on prod (and probably staging). Once run, https://imagecat.princeton.edu/guide_cards/29378 will have textual content.

**Comment by leefaisonr** [comment]
I have run the InfoCard import task on staging/production and we are now seeing the text for those links. Thank you!

<img width="1512" alt="image" src="https://github.com/pulibrary/imagecat-rails/assets/108823963/969d9ef1-608d-42cf-9c9f-62f14b00b652">
