### ISSUE TITLE
Import data from CSVs

### ISSUE THREAD

**Issue by leefaisonr** [pulibrary/imagecat-rails#17]
### Acceptance criteria

- [x] The database contains the data from the legacy system
- [x] There is documentation on how to load the dbs (local, staging, production) 
- [x] SubGuide cards are linked to their appropriate parent (which could be another SubGuide or Guide) 

### Implementation notes, if any

* Will need to have rails models in place 
* Add the CSVs to the repository 
* Since the SubGuideCard can be a child of either a GuideCard or another SubGuideCard, a simple belongs_to relationship does not work. We could try single table inheritance, but we think a lighter weight solution is to not record the relationship in the database at all and instead write access methods for parent and children of GuideCards and SubGuideCards

**Comment by hackartisan** [comment]
What is the path for a sub guide card show page? Is it:
* imagecat.princeton.edu/sub_guide_cards/8
* or imagecat.princeton.edu/guide_cards/3/sub_guide_cards/8
?

**Comment by hackartisan** [comment]
We learned key information: parent_id in subguides csv correlates to sortid in guides csv.
Path field is the folder in which the card images reside.
