### ISSUE TITLE
Submitting an empty search should take me to the beginning of the index

### ISSUE THREAD

**Issue by bess** [pulibrary/imagecat-rails#176]
### User story
As a user who is new to this application, when I first go to the front page, I see a "Go" Button. I push it and get an error. I'd rather see something meaningful, like the beginning of the card index. Anything but an error.

### Acceptance criteria
- [ ] If I submit an empty search, it is the same as if I submitted a "*" in the search box

**Comment by leefaisonr** [comment]
Closed by #196
