### ISSUE TITLE
Ensure Images are Backed Up 

### ISSUE THREAD

**Issue by leefaisonr** [pulibrary/imagecat-rails#21]
### Acceptance criteria

- [ ] We want to automate a backup process for the images and the database
- [ ] A one-time snapshot is sufficient 
- [ ] Ask Francis what the backup strategy is for an aws bucket  

### Implementation notes, if any

* Ask Francis 
* Note that this data will not change

**Comment by hackartisan** [comment]
The database is on the postgres cluster and so is covered by those backup practices. The images are on s3 which is very reliable; to the extent that backup is needed it should be approached in the context of everything served by that iiif endpoint.
