### ISSUE TITLE
Add use cases documentation

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/imagecat-rails#64]
Add the following use cases documentation either to the README or to a file called `docs/use_cases.md`

- When cards were converted to OCLC records, there were quality assurance issues. These scanned cards allow us to correct these errors when they come up. I encounter this every day.
- If we don’t correct the errors then people will be misled, e.g. notes about items held in another library, not at princeton
- There may be accession ids on the cards (used between 1900 and 1942 or 43) that match with entries in accession books, which have info about where we got the book and how much we paid for it. Very pertinent for rare books.
- Call #s may be on there that weren’t transferred.
- Law enforcement sometimes wants to know provenance -- proof of ownership and when we acquired an item.
- Historical view of library to a certain point in time, e.g. wrote an article about 3 millionth acquisition.
- Be able to print a single card and carry it into the stacks
-

**Comment by leefaisonr** [comment]
Closed by #65
