### ISSUE TITLE
Implement home page

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/imagecat-rails#67]
Instead of pointing root to the GuideCard index page, point to a home page with a search box (search box not required for this ticket).

**Comment by leefaisonr** [comment]
Welcome controller: https://github.com/pulibrary/pdc_describe/blob/main/app/controllers/welcome_controller.rb

**Comment by leefaisonr** [comment]
https://github.com/pulibrary/pdc_describe/commit/f9120c03c139becb7bba3fdcf257e1465bea7008

**Comment by leefaisonr** [comment]
#107 closes this ticket
